### PR TITLE
A Fix to adapt new padding style

### PR DESCRIPTION
**Pull request by Seas0**
I managed to make the Bash script work with the updated network login system by removing the reverse operation to password before padding

### CODE REVIEW

**Review by Seas0 — COMMENTED** [review]
Some gramma & spell errors included 😂

**Comment by Gaomengkai** [comment]
On May 16, 2021, the form of 'pw' has changed. Changes are listed as the following js:
`
        var macString = getQueryStringByName("mac");
        if(isNull(macString)){
        	macString="111111111";
        }`
 and 
`var passwordMac = password+">"+macString;
password = encryptedPassword(passwordMac);`

So I wish the author could do some updates. Thanks.

**Comment by Gaomengkai** [comment]
[login_bch.js?version=20210512](http://192.168.50.3:8081/eportal/interface/index_files/pc/login_bch.js?version=20210512)
[AuthInterFace.js?version=20210516](http://192.168.50.3:8081/eportal/interface/index_files/js/AuthInterFace.js?version=20210516)

**Comment by Seas0** [comment]
> [login_bch.js?version=20210512](http://192.168.50.3:8081/eportal/interface/index_files/pc/login_bch.js?version=20210512)
> [AuthInterFace.js?version=20210516](http://192.168.50.3:8081/eportal/interface/index_files/js/AuthInterFace.js?version=20210516)

I may look into it later, after sorts of chores 😂

**Comment by Seas0** [comment]
> [login_bch.js?version=20210512](http://192.168.50.3:8081/eportal/interface/index_files/pc/login_bch.js?version=20210512)
> [AuthInterFace.js?version=20210516](http://192.168.50.3:8081/eportal/interface/index_files/js/AuthInterFace.js?version=20210516)

You may use the unencrypted version of the script (or switch to another login program, like https://github.com/black-binary/hust-network-login , etc.) before any update is made.

**Comment by Gaomengkai** [comment]
I left a encrypted python version of PULL REQUEST for the original author @Cra1gTucker ... But I just think he/she doesn't have free time to update the project.

**Comment by Cra1gTucker** [comment]
Sorry guys, been really busy this term. Funny thing is that I didn't even receive an email from GitHub for this PR. Considering final exams are coming, I'm afraid I won't be able to review your code in the coming weeks. So I'll just merge this pull request first. Big thanks to all of you who actually care about this almost useless project!

**Pull request merged**
